# Banking Data - Load Raw CSV Files

This notebook loads raw CSV files from the data folder for initial exploration and analysis.

# Setup

In [1]:
%pip install pandas numpy ipython

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (2.0.2)
Requirement already satisfied: ipython in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (8.18.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.1)
Requirement already satisfied: pytz>=2020.1 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: matplotlib-inline in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (0.2.1)
Requirement already satisfied: decorator in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (5.2.1)
Requirement already satisfied: exceptiongroup in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (1.3.1)
Requirement already satisfied: stack-data in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (0.6.3)
Requirement already satisfied: jedi>=0.16 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (0.19.2)
Requirement already satisfied: typing-extensions in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (4.15.0)
Requirement already satisfied: pygments>=2.4.0 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (2.20.0)
Requirement already satisfied: pexpect>4.3 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (4.9.0)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (3.0.52)
Requirement already satisfied: traitlets>=5 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from ipython) (5.14.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from jedi>=0.16->ipython) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from pexpect>4.3->ipython) (0.7.0)
Requirement already satisfied: wcwidth in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython) (0.6.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: executing>=1.2.0 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython) (3.0.1)
Requirement already satisfied: pure-eval in /Users/ahmedaljahdali/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython) (0.2.3)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

## Import Required Libraries

Import necessary libraries for data manipulation and file handling.

In [2]:
import pandas as pd
import numpy as np
import os
import glob
from datetime import datetime

print("Libraries imported successfully!")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Libraries imported successfully!
Pandas version: 2.3.3
NumPy version: 2.0.2

## Locate CSV Files in Data Folder

Find all CSV files in the data directory.

In [3]:
# Define the data folder path
data_folder = 'data'

# List all CSV files in the data folder
csv_files = glob.glob(os.path.join(data_folder, '*.csv'))

print(f"Found {len(csv_files)} CSV files in the data folder:\n")
for file in sorted(csv_files):
    file_name = os.path.basename(file)
    file_size = os.path.getsize(file) / (1024 * 1024)  # Size in MB
    print(f"  - {file_name:20s} ({file_size:.2f} MB)")

Found 8 CSV files in the data folder:

  - account.csv          (0.15 MB)
  - card.csv             (0.03 MB)
  - client.csv           (0.09 MB)
  - disp.csv             (0.12 MB)
  - district.csv         (0.01 MB)
  - loan.csv             (0.03 MB)
  - order.csv            (0.26 MB)
  - trans.csv            (66.19 MB)

## Load All CSV Files

Load each CSV file into a pandas DataFrame. All files use semicolon (`;`) as delimiter.

In [4]:
# Define CSV file names
csv_file_names = ['account.csv', 'card.csv', 'client.csv', 'disp.csv', 
                  'district.csv', 'loan.csv', 'order.csv', 'trans.csv']

# Load all CSV files into a dictionary
datasets = {}
load_errors = []

for file_name in csv_file_names:
    file_path = os.path.join(data_folder, file_name)
    try:
        # Load with semicolon delimiter
        df = pd.read_csv(file_path, sep=';', low_memory=False)
        datasets[file_name.replace('.csv', '')] = df
        print(f"Loaded {file_name:20s} - Shape: {df.shape}")
    except Exception as e:
        load_errors.append(f"{file_name}: {str(e)}")
        print(f"Error loading {file_name}: {str(e)}")

print(f"\n{'='*60}")
print(f"Successfully loaded: {len(datasets)}/{len(csv_file_names)} files")
if load_errors:
    print(f"Errors: {len(load_errors)}")
    for error in load_errors:
        print(f"  - {error}")

Loaded account.csv          - Shape: (4500, 4)
Loaded card.csv             - Shape: (892, 4)
Loaded client.csv           - Shape: (5369, 3)
Loaded disp.csv             - Shape: (5369, 4)
Loaded district.csv         - Shape: (77, 16)
Loaded loan.csv             - Shape: (682, 7)
Loaded order.csv            - Shape: (6471, 6)
Loaded trans.csv            - Shape: (1056320, 10)

============================================================
Successfully loaded: 8/8 files

## Display Dataset Information

Show basic information about each loaded dataset including column names and data types.

In [5]:
# Display information for each dataset
for name, df in datasets.items():
    print(f"\n{'='*70}")
    print(f"Dataset: {name.upper()}")
    print(f"{'='*70}")
    print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"\nColumns: {list(df.columns)}")
    print(f"\nData Types:\n{df.dtypes.to_string()}")
    print(f"\nMissing Values: {df.isnull().sum().sum():,}")
    print(f"\nFirst 3 rows:")
    display(df.head(3))

======================================================================
Dataset: ACCOUNT
======================================================================
Shape: 4,500 rows × 4 columns

Columns: ['account_id', 'district_id', 'frequency', 'date']

Data Types:
account_id      int64
district_id     int64
frequency      object
date            int64

Missing Values: 0

First 3 rows:

   account_id  district_id         frequency    date
0         576           55  POPLATEK MESICNE  930101
1        3818           74  POPLATEK MESICNE  930101
2         704           55  POPLATEK MESICNE  930101

======================================================================
Dataset: CARD
======================================================================
Shape: 892 rows × 4 columns

Columns: ['card_id', 'disp_id', 'type', 'issued']

Data Types:
card_id     int64
disp_id     int64
type       object
issued     object

Missing Values: 0

First 3 rows:

   card_id  disp_id     type           issued
0     1005     9285  classic  931107 00:00:00
1      104      588  classic  940119 00:00:00
2      747     4915  classic  940205 00:00:00

======================================================================
Dataset: CLIENT
======================================================================
Shape: 5,369 rows × 3 columns

Columns: ['client_id', 'birth_number', 'district_id']

Data Types:
client_id       int64
birth_number    int64
district_id     int64

Missing Values: 0

First 3 rows:

   client_id  birth_number  district_id
0          1        706213           18
1          2        450204            1
2          3        406009            1

======================================================================
Dataset: DISP
======================================================================
Shape: 5,369 rows × 4 columns

Columns: ['disp_id', 'client_id', 'account_id', 'type']

Data Types:
disp_id        int64
client_id      int64
account_id     int64
type          object

Missing Values: 0

First 3 rows:

   disp_id  client_id  account_id       type
0        1          1           1      OWNER
1        2          2           2      OWNER
2        3          3           2  DISPONENT

======================================================================
Dataset: DISTRICT
======================================================================
Shape: 77 rows × 16 columns

Columns: ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16']

Data Types:
A1       int64
A2      object
A3      object
A4       int64
A5       int64
A6       int64
A7       int64
A8       int64
A9       int64
A10    float64
A11      int64
A12     object
A13    float64
A14      int64
A15     object
A16      int64

Missing Values: 0

First 3 rows:

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16
0,1,Hl.m. Praha,Prague,1204953,0,0,0,1,1,100.0,12541,0.29,0.43,167,85677,99107
1,2,Benesov,central Bohemia,88884,80,26,6,2,5,46.7,8507,1.67,1.85,132,2159,2674
2,3,Beroun,central Bohemia,75232,55,26,4,1,5,41.7,8980,1.95,2.21,111,2824,2813

======================================================================
Dataset: LOAN
======================================================================
Shape: 682 rows × 7 columns

Columns: ['loan_id', 'account_id', 'date', 'amount', 'duration', 'payments', 'status']

Data Types:
loan_id         int64
account_id      int64
date            int64
amount          int64
duration        int64
payments      float64
status         object

Missing Values: 0

First 3 rows:

   loan_id  account_id    date  amount  duration  payments status
0     5314        1787  930705   96396        12    8033.0      B
1     5316        1801  930711  165960        36    4610.0      A
2     6863        9188  930728  127080        60    2118.0      A

======================================================================
Dataset: ORDER
======================================================================
Shape: 6,471 rows × 6 columns

Columns: ['order_id', 'account_id', 'bank_to', 'account_to', 'amount', 'k_symbol']

Data Types:
order_id        int64
account_id      int64
bank_to        object
account_to      int64
amount        float64
k_symbol       object

Missing Values: 0

First 3 rows:

   order_id  account_id bank_to  account_to  amount k_symbol
0     29401           1      YZ    87144583  2452.0     SIPO
1     29402           2      ST    89597016  3372.7     UVER
2     29403           2      QR    13943797  7266.0     SIPO

======================================================================
Dataset: TRANS
======================================================================
Shape: 1,056,320 rows × 10 columns

Columns: ['trans_id', 'account_id', 'date', 'type', 'operation', 'amount', 'balance', 'k_symbol', 'bank', 'account']

Data Types:
trans_id        int64
account_id      int64
date            int64
type           object
operation      object
amount        float64
balance       float64
k_symbol       object
bank           object
account       float64

Missing Values: 2,208,738

First 3 rows:

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN

## Summary

Quick summary of all loaded datasets.

In [6]:
# Create summary table
import pandas as pd

summary_data = []
for name, df in datasets.items():
    summary_data.append({
        'Dataset': name,
        'Rows': df.shape[0],
        'Columns': df.shape[1],
        'Missing Values': df.isnull().sum().sum(),
        'Memory (MB)': round(df.memory_usage(deep=True).sum() / (1024**2), 2)
    })

summary_df = pd.DataFrame(summary_data)
print("\n" + "="*70)
print("DATASET SUMMARY")
print("="*70)
print(summary_df.to_string(index=False))
print("="*70)
print(f"Total Rows: {summary_df['Rows'].sum():,}")
print(f"Total Memory: {summary_df['Memory (MB)'].sum():.2f} MB")
print("="*70)

======================================================================
DATASET SUMMARY
======================================================================
 Dataset    Rows  Columns  Missing Values  Memory (MB)
 account    4500        4               0         0.42
    card     892        4               0         0.13
  client    5369        3               0         0.12
    disp    5369        4               0         0.44
district      77       16               0         0.03
    loan     682        7               0         0.07
   order    6471        6               0         0.94
   trans 1056320       10         2208738       258.44
======================================================================
Total Rows: 1,079,680
Total Memory: 260.59 MB
======================================================================

## Date Column Cleaning

Convert integer date formats (YYMMDD) to proper datetime objects for analysis.

In [7]:
print("=" * 70)
print("DATE CLEANING - Before")
print("=" * 70)

# Show current date columns and their formats
date_info = {
    'account': {'column': 'date', 'sample': datasets['account']['date'].head(3).tolist()},
    'loan': {'column': 'date', 'sample': datasets['loan']['date'].head(3).tolist()},
    'trans': {'column': 'date', 'sample': datasets['trans']['date'].head(3).tolist()},
    'card': {'column': 'issued', 'sample': datasets['card']['issued'].head(3).tolist()}
}

for dataset_name, info in date_info.items():
    print(f"\n{dataset_name.upper()}.{info['column']}:")
    print(f"  Type: {datasets[dataset_name][info['column']].dtype}")
    print(f"  Sample values: {info['sample']}")

print("\n" + "=" * 70)
print("Converting integer dates (YYMMDD format) to datetime...")
print("=" * 70)

======================================================================
DATE CLEANING - Before
======================================================================

ACCOUNT.date:
  Type: int64
  Sample values: [930101, 930101, 930101]

LOAN.date:
  Type: int64
  Sample values: [930705, 930711, 930728]

TRANS.date:
  Type: int64
  Sample values: [930101, 930101, 930101]

CARD.issued:
  Type: object
  Sample values: ['931107 00:00:00', '940119 00:00:00', '940205 00:00:00']

======================================================================
Converting integer dates (YYMMDD format) to datetime...
======================================================================

In [8]:
def convert_int_to_date(date_int):
    """
    Convert integer date format (YYMMDD) to date only (no time).
    Example: 930101 -> 1993-01-01
    """
    date_str = str(int(date_int))
    year = int(date_str[:2])
    month = int(date_str[2:4])
    day = int(date_str[4:6])
    
    # Assume years 00-30 are 2000s, 31-99 are 1900s
    if year <= 30:
        year += 2000
    else:
        year += 1900
    
    return pd.to_datetime(f"{year}-{month:02d}-{day:02d}").date()

# Convert integer date columns
print("\nConverting ACCOUNT.date...")
datasets['account']['date'] = datasets['account']['date'].apply(convert_int_to_date)
print(f"Converted {len(datasets['account'])} rows")

print("\nConverting LOAN.date...")
datasets['loan']['date'] = datasets['loan']['date'].apply(convert_int_to_date)
print(f"Converted {len(datasets['loan'])} rows")

print("\nConverting TRANS.date...")
datasets['trans']['date'] = datasets['trans']['date'].apply(convert_int_to_date)
print(f"Converted {len(datasets['trans'])} rows")

print("\nConverting CARD.issued...")
# Card issued is already in string format like "931107 00:00:00"
# Extract YYMMDD part and convert
datasets['card']['issued'] = datasets['card']['issued'].str[:6].astype(int).apply(convert_int_to_date)
print(f"Converted {len(datasets['card'])} rows")

print("\n" + "=" * 70)
print("Date conversion completed successfully!")
print("=" * 70)

Converting ACCOUNT.date...
Converted 4500 rows

Converting LOAN.date...
Converted 682 rows

Converting TRANS.date...
Converted 1056320 rows

Converting CARD.issued...
Converted 892 rows

======================================================================
Date conversion completed successfully!
======================================================================

In [9]:
print("\n" + "=" * 70)
print("DATE CLEANING - After")
print("=" * 70)

# Show updated date columns and their formats
for dataset_name, info in date_info.items():
    col = info['column']
    print(f"\n{dataset_name.upper()}.{col}:")
    print(f"  Type: {datasets[dataset_name][col].dtype}")
    print(f"  Sample values: {datasets[dataset_name][col].head(3).tolist()}")
    print(f"  Date range: {datasets[dataset_name][col].min()} to {datasets[dataset_name][col].max()}")

print("\n" + "=" * 70)
print("Summary: All date columns converted to date format (no time)")
print("=" * 70)

======================================================================
DATE CLEANING - After
======================================================================

ACCOUNT.date:
  Type: object
  Sample values: [datetime.date(1993, 1, 1), datetime.date(1993, 1, 1), datetime.date(1993, 1, 1)]
  Date range: 1993-01-01 to 1997-12-29

LOAN.date:
  Type: object
  Sample values: [datetime.date(1993, 7, 5), datetime.date(1993, 7, 11), datetime.date(1993, 7, 28)]
  Date range: 1993-07-05 to 1998-12-08

TRANS.date:
  Type: object
  Sample values: [datetime.date(1993, 1, 1), datetime.date(1993, 1, 1), datetime.date(1993, 1, 1)]
  Date range: 1993-01-01 to 1998-12-31

CARD.issued:
  Type: object
  Sample values: [datetime.date(1993, 11, 7), datetime.date(1994, 1, 19), datetime.date(1994, 2, 5)]
  Date range: 1993-11-07 to 1998-12-29

======================================================================
Summary: All date columns converted to date format (no time)
======================================================================

**Date Cleaning Summary:**
- Converted integer date format (YYMMDD) to proper date objects (no time component)
- Applied to: account.date, loan.date, trans.date, card.issued
- Year interpretation: 00-30 → 2000s, 31-99 → 1900s
- All dates now normalized for time-series analysis

## Client Birth Number Processing

Extract birthday and age from the birth_number field in the client dataset.

In [10]:
print("=" * 70)
print("CLIENT BIRTH NUMBER - Before Processing")
print("=" * 70)

print(f"\nClient dataset shape: {datasets['client'].shape}")
print(f"Current columns: {list(datasets['client'].columns)}")
print(f"\nBirth number samples:")
print(datasets['client']['birth_number'].head(10).to_string())
print(f"\nBirth number data type: {datasets['client']['birth_number'].dtype}")

======================================================================
CLIENT BIRTH NUMBER - Before Processing
======================================================================

Client dataset shape: (5369, 3)
Current columns: ['client_id', 'birth_number', 'district_id']

Birth number samples:
0    706213
1    450204
2    406009
3    561201
4    605703
5    190922
6    290125
7    385221
8    351016
9    430501

Birth number data type: int64

In [11]:
from datetime import date

def parse_birth_number(birth_num):
    """
    Parse Czech birth number to extract birthday and gender.
    Format: YYMMDD (for males) or YY(MM+50)DD (for females)
    Example: 706213 -> 1970-12-13 (female, month 62 = 12 + 50)
             450204 -> 1945-02-04 (male)
    """
    birth_str = str(birth_num).zfill(6)
    year = int(birth_str[:2])
    month = int(birth_str[2:4])
    day = int(birth_str[4:6])
    
    # Check if female (month > 50)
    if month > 50:
        month -= 50
        gender = 'F'
    else:
        gender = 'M'
    
    # Determine century (00-30 = 2000s, 31-99 = 1900s)
    if year <= 30:
        year += 2000
    else:
        year += 1900
    
    birthday = date(year, month, day)
    
    return birthday, gender

print("\n" + "=" * 70)
print("Processing birth_number field...")
print("=" * 70)

# Apply the function to extract birthday and gender
datasets['client'][['birthday', 'gender']] = datasets['client']['birth_number'].apply(
    lambda x: pd.Series(parse_birth_number(x))
)

print(f"\nExtracted birthday and gender for {len(datasets['client'])} clients")

# Calculate age (as of 1998-12-31, the last date in the dataset)
reference_date = date(1998, 12, 31)
datasets['client']['age'] = datasets['client']['birthday'].apply(
    lambda bd: reference_date.year - bd.year - ((reference_date.month, reference_date.day) < (bd.month, bd.day))
)

print(f"Calculated age as of {reference_date}")
print("\n" + "=" * 70)
print("Birth number processing completed!")
print("=" * 70)

======================================================================
Processing birth_number field...
======================================================================

Extracted birthday and gender for 5369 clients
Calculated age as of 1998-12-31

======================================================================
Birth number processing completed!
======================================================================

In [12]:
print("\n" + "=" * 70)
print("CLIENT DATASET - After Processing")
print("=" * 70)

print(f"\nUpdated columns: {list(datasets['client'].columns)}")
print(f"\nSample data (first 10 rows):")
display(datasets['client'][['client_id', 'birth_number', 'birthday', 'gender', 'age', 'district_id']].head(10))

print("\n" + "=" * 70)
print("STATISTICS")
print("=" * 70)
print(f"\nGender distribution:")
print(datasets['client']['gender'].value_counts().to_string())

print(f"\n\nAge statistics:")
print(datasets['client']['age'].describe().to_string())

print(f"\n\nAge distribution:")
age_ranges = pd.cut(datasets['client']['age'], bins=[0, 20, 30, 40, 50, 60, 70, 150], 
                     labels=['0-20', '21-30', '31-40', '41-50', '51-60', '61-70', '70+'])
print(age_ranges.value_counts().sort_index().to_string())

print("\n" + "=" * 70)

======================================================================
CLIENT DATASET - After Processing
======================================================================

Updated columns: ['client_id', 'birth_number', 'district_id', 'birthday', 'gender', 'age']

Sample data (first 10 rows):

   client_id  birth_number    birthday gender  age  district_id
0          1        706213  1970-12-13      F   28           18
1          2        450204  1945-02-04      M   53            1
2          3        406009  1940-10-09      F   58            1
3          4        561201  1956-12-01      M   42            5
4          5        605703  1960-07-03      F   38            5
5          6        190922  2019-09-22      M  -21           12
6          7        290125  2029-01-25      M  -31           15
7          8        385221  1938-02-21      F   60           51
8          9        351016  1935-10-16      M   63           60
9         10        430501  1943-05-01      M   55           57

======================================================================
STATISTICS
======================================================================

Gender distribution:
gender
M    2724
F    2645


Age statistics:
count    5369.000000
mean       32.601974
std        25.512031
min       -32.000000
25%        23.000000
50%        37.000000
75%        51.000000
max        67.000000


Age distribution:
age
0-20     390
21-30    992
31-40    967
41-50    962
51-60    979
61-70    424
70+        0

======================================================================

**Birth Number Processing Summary:**
- Parsed birth_number field (YYMMDD format) to extract birthday and gender
- Gender identification: Month > 50 indicates female (month - 50 = actual month)
- Added 3 new columns to client dataset: `birthday`, `gender`, `age`
- Age calculated as of 1998-12-31 (end of dataset period)
- Client dataset now has complete demographic information

## District Column Renaming

Rename district.csv columns from codes (A1, A2, ..., A16) to descriptive names for better readability.

In [13]:
print("=" * 70)
print("DISTRICT COLUMNS - Before Renaming")
print("=" * 70)

print(f"\nDistrict dataset shape: {datasets['district'].shape}")
print(f"Current columns: {list(datasets['district'].columns)}")
print(f"\nSample data (first 3 rows):")
print(datasets['district'].head(3).to_string())
print("\n" + "=" * 70)

======================================================================
DISTRICT COLUMNS - Before Renaming
======================================================================

District dataset shape: (77, 16)
Current columns: ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16']

Sample data (first 3 rows):
   A1           A2               A3       A4  A5  A6  A7  A8  A9    A10    A11   A12   A13  A14    A15    A16
0   1  Hl.m. Praha           Prague  1204953   0   0   0   1   1  100.0  12541  0.29  0.43  167  85677  99107
1   2      Benesov  central Bohemia    88884  80  26   6   2   5   46.7   8507  1.67  1.85  132   2159   2674
2   3       Beroun  central Bohemia    75232  55  26   4   1   5   41.7   8980  1.95  2.21  111   2824   2813

======================================================================

In [14]:
print("\n" + "=" * 70)
print("Renaming district columns...")
print("=" * 70)

# Define column name mapping from A1-A16 to descriptive names
district_column_mapping = {
    'A1': 'district_id',
    'A2': 'district_name',
    'A3': 'region',
    'A4': 'population',
    'A5': 'num_municipalities_0_499',
    'A6': 'num_municipalities_500_1999',
    'A7': 'num_municipalities_2000_9999',
    'A8': 'num_municipalities_10000_plus',
    'A9': 'num_cities',
    'A10': 'urban_population_ratio',
    'A11': 'average_salary',
    'A12': 'unemployment_rate_1995',
    'A13': 'unemployment_rate_1996',
    'A14': 'entrepreneurs_per_1000',
    'A15': 'crimes_1995',
    'A16': 'crimes_1996'
}

# Rename columns
datasets['district'] = datasets['district'].rename(columns=district_column_mapping)

print("\nColumn mapping applied:")
for old, new in district_column_mapping.items():
    print(f"  {old:5s} -> {new}")

print("\n" + "=" * 70)
print("District columns renamed successfully!")
print("=" * 70)

======================================================================
Renaming district columns...
======================================================================

Column mapping applied:
  A1    -> district_id
  A2    -> district_name
  A3    -> region
  A4    -> population
  A5    -> num_municipalities_0_499
  A6    -> num_municipalities_500_1999
  A7    -> num_municipalities_2000_9999
  A8    -> num_municipalities_10000_plus
  A9    -> num_cities
  A10   -> urban_population_ratio
  A11   -> average_salary
  A12   -> unemployment_rate_1995
  A13   -> unemployment_rate_1996
  A14   -> entrepreneurs_per_1000
  A15   -> crimes_1995
  A16   -> crimes_1996

======================================================================
District columns renamed successfully!
======================================================================

In [15]:
print("\n" + "=" * 70)
print("DISTRICT DATASET - After Renaming")
print("=" * 70)

print(f"\nUpdated columns: {list(datasets['district'].columns)}")
print(f"\nColumn data types:")
print(datasets['district'].dtypes.to_string())

print(f"\n\nSample data (first 5 rows):")
print(datasets['district'].head(5).to_string())

print(f"\n\nDataset statistics:")
print(f"  Total districts: {len(datasets['district'])}")
print(f"  Total population: {datasets['district']['population'].sum():,}")
print(f"  Average salary (mean): {datasets['district']['average_salary'].mean():,.2f}")
print(f"  Unemployment 1996 (mean): {datasets['district']['unemployment_rate_1996'].mean():.2f}%")

print("\n" + "=" * 70)

======================================================================
DISTRICT DATASET - After Renaming
======================================================================

Updated columns: ['district_id', 'district_name', 'region', 'population', 'num_municipalities_0_499', 'num_municipalities_500_1999', 'num_municipalities_2000_9999', 'num_municipalities_10000_plus', 'num_cities', 'urban_population_ratio', 'average_salary', 'unemployment_rate_1995', 'unemployment_rate_1996', 'entrepreneurs_per_1000', 'crimes_1995', 'crimes_1996']

Column data types:
district_id                        int64
district_name                     object
region                            object
population                         int64
num_municipalities_0_499           int64
num_municipalities_500_1999        int64
num_municipalities_2000_9999       int64
num_municipalities_10000_plus      int64
num_cities                         int64
urban_population_ratio           float64
average_salary                     int64
unemployment_rate_1995            object
unemployment_rate_1996           float64
entrepreneurs_per_1000             int64
crimes_1995                       object
crimes_1996                        int64


Sample data (first 5 rows):
   district_id district_name           region  population  num_municipalities_0_499  num_municipalities_500_1999  num_municipalities_2000_9999  num_municipalities_10000_plus  num_cities  urban_population_ratio  average_salary unemployment_rate_1995  unemployment_rate_1996  entrepreneurs_per_1000 crimes_1995  crimes_1996
0            1   Hl.m. Praha           Prague     1204953                         0                            0                             0                              1           1                   100.0           12541                   0.29                    0.43                     167       85677        99107
1            2       Benesov  central Bohemia       88884                        80                           26                             6                              2           5                    46.7            8507                   1.67                    1.85                     132        2159         2674
2            3        Beroun  central Bohemia       75232                        55                           26                             4                              1           5                    41.7            8980                   1.95                    2.21                     111        2824         2813
3            4        Kladno  central Bohemia      149893                        63                           29                             6                              2           6                    67.4            9753                   4.64                    5.05                     109        5244         5892
4            5         Kolin  central Bohemia       95616                        65                           30                             4                              1           6                    51.4            9307                   3.85                    4.43                     118        2616         3040


Dataset statistics:
  Total districts: 77
  Total population: 10,309,137
  Average salary (mean): 9,031.68
  Unemployment 1996 (mean): 3.79%

======================================================================

**District Column Renaming Summary:**
- Renamed all 16 columns from codes (A1-A16) to descriptive names
- Column meanings:
  - **district_id**: Unique district identifier
  - **district_name**: Name of the district
  - **region**: Geographic region
  - **population**: Total population
  - **num_municipalities_X**: Count of municipalities by population size
  - **num_cities**: Number of cities in district
  - **urban_population_ratio**: Percentage of urban population
  - **average_salary**: Average salary in the district
  - **unemployment_rate_1995/1996**: Unemployment rates
  - **entrepreneurs_per_1000**: Number of entrepreneurs per 1000 inhabitants
  - **crimes_1995/1996**: Number of committed crimes
- District dataset now has human-readable column names for analysis

## Data Type Verification

Check and verify data types for all datasets to ensure proper format.

In [16]:
print("=" * 70)
print("DATA TYPE VERIFICATION FOR ALL DATASETS")
print("=" * 70)

for dataset_name, df in datasets.items():
    print(f"\n{'='*70}")
    print(f"Dataset: {dataset_name.upper()}")
    print(f"{'='*70}")
    print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"\nColumn Data Types:")
    print("-" * 50)
    
    dtype_info = []
    for col in df.columns:
        dtype = str(df[col].dtype)
        non_null = df[col].count()
        null_count = df[col].isnull().sum()
        
        # Show sample values
        sample = df[col].dropna().head(2).tolist()
        sample_str = str(sample)[:50] + "..." if len(str(sample)) > 50 else str(sample)
        
        print(f"  {col:20s} | {dtype:15s} | Non-null: {non_null:7,} | Sample: {sample_str}")
    
    print()

print("=" * 70)
print("Data type verification completed!")
print("=" * 70)

======================================================================
DATA TYPE VERIFICATION FOR ALL DATASETS
======================================================================

======================================================================
Dataset: ACCOUNT
======================================================================
Shape: 4,500 rows × 4 columns

Column Data Types:
--------------------------------------------------
  account_id           | int64           | Non-null:   4,500 | Sample: [576, 3818]
  district_id          | int64           | Non-null:   4,500 | Sample: [55, 74]
  frequency            | object          | Non-null:   4,500 | Sample: ['POPLATEK MESICNE', 'POPLATEK MESICNE']
  date                 | object          | Non-null:   4,500 | Sample: [datetime.date(1993, 1, 1), datetime.date(1993, 1,...


======================================================================
Dataset: CARD
======================================================================
Shape: 892 rows × 4 columns

Column Data Types:
--------------------------------------------------
  card_id              | int64           | Non-null:     892 | Sample: [1005, 104]
  disp_id              | int64           | Non-null:     892 | Sample: [9285, 588]
  type                 | object          | Non-null:     892 | Sample: ['classic', 'classic']
  issued               | object          | Non-null:     892 | Sample: [datetime.date(1993, 11, 7), datetime.date(1994, 1...


======================================================================
Dataset: CLIENT
======================================================================
Shape: 5,369 rows × 6 columns

Column Data Types:
--------------------------------------------------
  client_id            | int64           | Non-null:   5,369 | Sample: [1, 2]
  birth_number         | int64           | Non-null:   5,369 | Sample: [706213, 450204]
  district_id          | int64           | Non-null:   5,369 | Sample: [18, 1]
  birthday             | object          | Non-null:   5,369 | Sample: [datetime.date(1970, 12, 13), datetime.date(1945, ...
  gender               | object          | Non-null:   5,369 | Sample: ['F', 'M']
  age                  | int64           | Non-null:   5,369 | Sample: [28, 53]


======================================================================
Dataset: DISP
======================================================================
Shape: 5,369 rows × 4 columns

Column Data Types:
--------------------------------------------------
  disp_id              | int64           | Non-null:   5,369 | Sample: [1, 2]
  client_id            | int64           | Non-null:   5,369 | Sample: [1, 2]
  account_id           | int64           | Non-null:   5,369 | Sample: [1, 2]
  type                 | object          | Non-null:   5,369 | Sample: ['OWNER', 'OWNER']


======================================================================
Dataset: DISTRICT
======================================================================
Shape: 77 rows × 16 columns

Column Data Types:
--------------------------------------------------
  district_id          | int64           | Non-null:      77 | Sample: [1, 2]
  district_name        | object          | Non-null:      77 | Sample: ['Hl.m. Praha', 'Benesov']
  region               | object          | Non-null:      77 | Sample: ['Prague', 'central Bohemia']
  population           | int64           | Non-null:      77 | Sample: [1204953, 88884]
  num_municipalities_0_499 | int64           | Non-null:      77 | Sample: [0, 80]
  num_municipalities_500_1999 | int64           | Non-null:      77 | Sample: [0, 26]
  num_municipalities_2000_9999 | int64           | Non-null:      77 | Sample: [0, 6]
  num_municipalities_10000_plus | int64           | Non-null:      77 | Sample: [1, 2]
  num_cities           | int64           | Non-null:      77 | Sample: [1, 5]
  urban_population_ratio | float64         | Non-null:      77 | Sample: [100.0, 46.7]
  average_salary       | int64           | Non-null:      77 | Sample: [12541, 8507]
  unemployment_rate_1995 | object          | Non-null:      77 | Sample: ['0.29', '1.67']
  unemployment_rate_1996 | float64         | Non-null:      77 | Sample: [0.43, 1.85]
  entrepreneurs_per_1000 | int64           | Non-null:      77 | Sample: [167, 132]
  crimes_1995          | object          | Non-null:      77 | Sample: ['85677', '2159']
  crimes_1996          | int64           | Non-null:      77 | Sample: [99107, 2674]


======================================================================
Dataset: LOAN
======================================================================
Shape: 682 rows × 7 columns

Column Data Types:
--------------------------------------------------
  loan_id              | int64           | Non-null:     682 | Sample: [5314, 5316]
  account_id           | int64           | Non-null:     682 | Sample: [1787, 1801]
  date                 | object          | Non-null:     682 | Sample: [datetime.date(1993, 7, 5), datetime.date(1993, 7,...
  amount               | int64           | Non-null:     682 | Sample: [96396, 165960]
  duration             | int64           | Non-null:     682 | Sample: [12, 36]
  payments             | float64         | Non-null:     682 | Sample: [8033.0, 4610.0]
  status               | object          | Non-null:     682 | Sample: ['B', 'A']


======================================================================
Dataset: ORDER
======================================================================
Shape: 6,471 rows × 6 columns

Column Data Types:
--------------------------------------------------
  order_id             | int64           | Non-null:   6,471 | Sample: [29401, 29402]
  account_id           | int64           | Non-null:   6,471 | Sample: [1, 2]
  bank_to              | object          | Non-null:   6,471 | Sample: ['YZ', 'ST']
  account_to           | int64           | Non-null:   6,471 | Sample: [87144583, 89597016]
  amount               | float64         | Non-null:   6,471 | Sample: [2452.0, 3372.7]
  k_symbol             | object          | Non-null:   6,471 | Sample: ['SIPO', 'UVER']


======================================================================
Dataset: TRANS
======================================================================
Shape: 1,056,320 rows × 10 columns

Column Data Types:
--------------------------------------------------
  trans_id             | int64           | Non-null: 1,056,320 | Sample: [695247, 171812]
  account_id           | int64           | Non-null: 1,056,320 | Sample: [2378, 576]
  date                 | object          | Non-null: 1,056,320 | Sample: [datetime.date(1993, 1, 1), datetime.date(1993, 1,...
  type                 | object          | Non-null: 1,056,320 | Sample: ['PRIJEM', 'PRIJEM']
  operation            | object          | Non-null: 873,206 | Sample: ['VKLAD', 'VKLAD']
  amount               | float64         | Non-null: 1,056,320 | Sample: [700.0, 900.0]
  balance              | float64         | Non-null: 1,056,320 | Sample: [700.0, 900.0]
  k_symbol             | object          | Non-null: 574,439 | Sample: ['DUCHOD', 'DUCHOD']
  bank                 | object          | Non-null: 273,508 | Sample: ['YZ', 'IJ']
  account              | float64         | Non-null: 295,389 | Sample: [62457513.0, 6149286.0]

======================================================================
Data type verification completed!
======================================================================

## Export Cleaned Datasets to CSV

Save each cleaned dataset to individual CSV files in the cleandata folder.

In [17]:
# Create cleandata folder if it doesn't exist
output_folder = 'cleandata'
if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    print(f"Created folder: {output_folder}")
else:
    print(f"Using existing folder: {output_folder}")

print("\n" + "=" * 70)
print("EXPORTING CLEANED DATASETS TO CSV")
print("=" * 70)

# Save each dataset to CSV
export_summary = []
for dataset_name, df in datasets.items():
    output_file = os.path.join(output_folder, f"{dataset_name}.csv")
    
    try:
        # Save with semicolon delimiter to match original format
        df.to_csv(output_file, sep=';', index=False)
        
        file_size = os.path.getsize(output_file) / (1024 * 1024)  # Size in MB
        
        export_summary.append({
            'Dataset': dataset_name,
            'Rows': df.shape[0],
            'Columns': df.shape[1],
            'File Size (MB)': round(file_size, 2),
            'Status': 'Success'
        })
        
        print(f"Exported {dataset_name:15s} | {df.shape[0]:7,} rows × {df.shape[1]:2d} cols | {file_size:6.2f} MB")
        
    except Exception as e:
        export_summary.append({
            'Dataset': dataset_name,
            'Rows': df.shape[0],
            'Columns': df.shape[1],
            'File Size (MB)': 0,
            'Status': f'Error: {str(e)}'
        })
        print(f"Error exporting {dataset_name}: {str(e)}")

print("\n" + "=" * 70)
print("EXPORT SUMMARY")
print("=" * 70)
export_df = pd.DataFrame(export_summary)
print(export_df.to_string(index=False))
print("=" * 70)
print(f"\nTotal files exported: {len([s for s in export_summary if s['Status'] == 'Success'])}/{len(datasets)}")
print(f"Total size: {export_df['File Size (MB)'].sum():.2f} MB")
print(f"Output location: {os.path.abspath(output_folder)}")
print("=" * 70)

Using existing folder: cleandata

======================================================================
EXPORTING CLEANED DATASETS TO CSV
======================================================================
Exported account         |   4,500 rows ×  4 cols |   0.15 MB
Exported card            |     892 rows ×  4 cols |   0.02 MB
Exported client          |   5,369 rows ×  6 cols |   0.16 MB
Exported disp            |   5,369 rows ×  4 cols |   0.11 MB
Exported district        |      77 rows × 16 cols |   0.01 MB
Exported loan            |     682 rows ×  7 cols |   0.03 MB
Exported order           |   6,471 rows ×  6 cols |   0.21 MB
Exported trans           | 1,056,320 rows × 10 cols |  60.59 MB

======================================================================
EXPORT SUMMARY
======================================================================
 Dataset    Rows  Columns  File Size (MB)  Status
 account    4500        4            0.15 Success
    card     892        4            0.02 Success
  client    5369        6            0.16 Success
    disp    5369        4            0.11 Success
district      77       16            0.01 Success
    loan     682        7            0.03 Success
   order    6471        6            0.21 Success
   trans 1056320       10           60.59 Success
======================================================================

Total files exported: 8/8
Total size: 61.28 MB
Output location: /Users/ahmedaljahdali/Desktop/pre processing/cleandata
======================================================================

**Export Summary:**
- All cleaned datasets exported to `cleandata/` folder
- Files saved with semicolon (`;`) delimiter
- Includes all transformations:
  - Date columns converted to date format (account, loan, trans, card)
  - Client dataset enhanced with birthday, gender, and age columns
- Each dataset saved as individual CSV file
- Ready for further analysis or sharing